/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jayasurya Aasaithambi (https://sketchfab.com/jayasurya00098)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/wedding-cake-a8bebb0d1a2646549ef42b60e1e85ded
title: Wedding Cake
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'





export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wedCake.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale = {1.2}>
      <group rotation={[-Math.PI / 2, 0, 0]} >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 10, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cake_3_Cake_0.geometry} material={materials.Cake} material-color = {props.customColors.mesh} />
          </group>
          <group position={[0, 110, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={props.customScale.scale}>
            <mesh geometry={nodes.Cake_2_Cake_0.geometry} material={materials.Cake}/>
          </group>
          
          <group position={[0, 180, 0]} rotation={[-Math.PI / 2, 0, 0]} >
            <mesh geometry={nodes.Cake_1_Cake_0.geometry} material={materials.Cake}/>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/wedCake.gltf')